version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:minhtam123@host.docker.internal:5432/studentdb
      - LOCAL_DATABASE_URL=postgresql://postgres:minhtam123@host.docker.internal:5432/studentdb
    depends_on:
      - redis